// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using darkstorm_api.Models;

#nullable disable

namespace darkstorm_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231010054054_AddGuidToProduct")]
    partial class AddGuidToProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("darkstorm_api.Models.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CPU")
                        .HasColumnType("longtext");

                    b.Property<float?>("Display")
                        .HasColumnType("float");

                    b.Property<bool?>("FalseTone")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("GPU")
                        .HasColumnType("longtext");

                    b.Property<int?>("HardDisk")
                        .HasColumnType("int");

                    b.Property<string>("HardDiskName")
                        .HasColumnType("longtext");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("longtext");

                    b.Property<string>("Model")
                        .HasColumnType("longtext");

                    b.Property<int?>("NumberOfPorts")
                        .HasColumnType("int");

                    b.Property<double?>("Price")
                        .HasColumnType("double");

                    b.Property<int?>("Quality")
                        .HasColumnType("int");

                    b.Property<int?>("RAM")
                        .HasColumnType("int");

                    b.Property<string>("RamName")
                        .HasColumnType("longtext");

                    b.Property<int?>("RefreshRate")
                        .HasColumnType("int");

                    b.Property<string>("Resolution")
                        .HasColumnType("longtext");

                    b.Property<bool?>("TrueTone")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("46e0f1cd-a0a4-40ed-8f29-10d32de6ebd8"),
                            CPU = "Intel Core i7 gen8",
                            Display = 15f,
                            FalseTone = false,
                            GPU = "GTX GEFORCE",
                            HardDisk = 512,
                            HardDiskName = "SSD512",
                            Manufacturer = "Asus",
                            Model = "Rog Strix G15",
                            NumberOfPorts = 5,
                            Price = 750.89999999999998,
                            Quality = 1080,
                            RAM = 8,
                            RefreshRate = 144,
                            TrueTone = true,
                            Year = 2021
                        },
                        new
                        {
                            ProductId = new Guid("a2edf0ac-d770-4510-8dfc-3168952edb3f"),
                            CPU = "Apple M2",
                            Display = 16f,
                            FalseTone = false,
                            GPU = "M2",
                            HardDisk = 512,
                            HardDiskName = "SSD512",
                            Manufacturer = "Apple",
                            Model = "Mac Book Pro 16",
                            NumberOfPorts = 5,
                            Price = 2789.9899999999998,
                            Quality = 2098,
                            RAM = 16,
                            RefreshRate = 144,
                            TrueTone = true,
                            Year = 2022
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
