// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using darkstorm_api.Models;

#nullable disable

namespace darkstorm_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231010050453_Update_GUID")]
    partial class Update_GUID
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("darkstorm_api.Models.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CPU")
                        .HasColumnType("longtext");

                    b.Property<float?>("Display")
                        .HasColumnType("float");

                    b.Property<bool?>("FalseTone")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("GPU")
                        .HasColumnType("longtext");

                    b.Property<int?>("HardDisk")
                        .HasColumnType("int");

                    b.Property<string>("HardDiskName")
                        .HasColumnType("longtext");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("longtext");

                    b.Property<string>("Model")
                        .HasColumnType("longtext");

                    b.Property<int?>("NumberOfPorts")
                        .HasColumnType("int");

                    b.Property<double?>("Price")
                        .HasColumnType("double");

                    b.Property<int?>("Quality")
                        .HasColumnType("int");

                    b.Property<int?>("RAM")
                        .HasColumnType("int");

                    b.Property<string>("RamName")
                        .HasColumnType("longtext");

                    b.Property<int?>("RefreshRate")
                        .HasColumnType("int");

                    b.Property<string>("Resolution")
                        .HasColumnType("longtext");

                    b.Property<bool?>("TrueTone")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
